### ISSUE TITLE
composer command

### ISSUE THREAD

**Issue by smitakartit** [reichwebconsulting/endicia-client#2]
Please send  composer comamnd
composer require endicia-client  not working

**Comment by sf71** [comment]
for this to work, the package maintainer would have to submit this to packagist.org.

**Comment by iambrianreich** [comment]
> for this to work, the package maintainer would have to submit this to packagist.org.

If anyone is interested in using this work I'd encourage them to fork it and add it to packages. I haven't maintained or improve this package in ages and unfortunately I'm not in a position to continue doing so.
